version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  nginx:
    restart: unless-stopped
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/
    depends_on:
      - backend
      - frontend
    ports:
      - '3000:80'

  frontend:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./front
      dockerfile: ./Dockerfile

  backend:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./back
      dockerfile: ./Dockerfile

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    env_file:
      - .env
    command: start-dev
    ports:
      - '8080:8080'
    depends_on:
      - db
