version: "3"
services:
  nginx:
    restart: unless-stopped
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/
    depends_on:
      - backend
      - frontend
    ports:
    - "3000:80"

  frontend:
    restart: unless-stopped
    build: 
      context: ./front
      dockerfile: ./Dockerfile

  backend :
    restart: unless-stopped
    build: 
      context: ./back
      dockerfile: ./Dockerfile
    